name: CI
on:
  push:
    branches:
      - "**"
env:
  NODE_VERSION: 18.16.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: npm/action-setup@v2

      - name: Lint Application
        run: npm run lint --workspace src/index.ts

      - run: npm install --frozen-lockfile
      - run: npm run lint && npm run build
